global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nestjs-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app1:3000', 'app2:3000']
        labels:
          service: 'system-design-nestjs'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
